"""G4-TOOL-02：Gate 4 Structured Tool Agent 核心（纯确定性底座）。

公开 ToolSpec / ToolCall / ToolObservation / RegisteredTool / ToolRegistry /
ToolExecutor / ToolHandler 与错误码常量。本包不调用 LLM；真实只读工具由
default registry 显式装配。
"""

from core.tool_agent.action_parser import (
    ActionParseCategory,
    ActionParseResult,
    diagnose_agent_action_text,
    parse_agent_action_text,
    strict_json_loads_no_duplicates,
)
from core.tool_agent.actions import (
    ACTION_PROVIDER_ERROR,
    ACTION_TIMEOUT,
    AgentAction,
    AgentDecisionCallMetadata,
    AgentDecisionOutcome,
    FinalAnswerAction,
    RefuseAction,
    ToolCallAction,
)
from core.tool_agent.default_tools import build_readonly_tool_registry
from core.tool_agent.integration import (
    FROZEN_TOOL_MODEL,
    FROZEN_TOOL_PROVIDER,
    build_tool_agent_runtime,
)
from core.tool_agent.executor import ToolExecutor
from core.tool_agent.models import (
    ACTION_PARSE_FAILED,
    AGENT_BUDGET_EXCEEDED,
    AGENT_ERROR_CODES,
    INVALID_TOOL_ARGUMENTS,
    TOOL_AGENT_ERROR_CODES,
    TOOL_BUDGET_EXCEEDED,
    TOOL_ERROR_CODES,
    TOOL_EXECUTION_FAILED,
    TOOL_OBSERVATION_STATUSES,
    TOOL_PERMISSION_DENIED,
    TOOL_RESULT_INVALID,
    PROJECT_CONTEXT_FILE_NOT_FOUND,
    PROJECT_CONTEXT_FILE_UNREADABLE,
    PROJECT_CONTEXT_LINE_OUT_OF_RANGE,
    PROJECT_CONTEXT_PATH_NOT_ALLOWED,
    GIT_COMMAND_FAILED,
    GIT_DIFF_UNAVAILABLE,
    GIT_PATH_NOT_ALLOWED,
    GIT_REF_INVALID,
    GIT_REPOSITORY_UNAVAILABLE,
    UNKNOWN_TOOL,
    ToolCall,
    ToolExecutionError,
    ToolObservation,
    ToolSpec,
    json_deep_copy,
)
from core.tool_agent.openai_compatible import OpenAICompatibleAgentDecisionProvider
from core.tool_agent.decision_prompt import (
    DecisionPromptProfile,
    ENGINEERING_DECISION_PROMPT_PROFILE,
    ENGINEERING_DECISION_PROMPT_SHA256,
    ENGINEERING_DECISION_PROMPT_V2_PROFILE,
    ENGINEERING_DECISION_PROMPT_V2_SHA256,
    ENGINEERING_DECISION_PROMPT_V3_PROFILE,
    ENGINEERING_DECISION_PROMPT_V3_SHA256,
    ENGINEERING_MAX_OUTPUT_TOKENS,
    ENGINEERING_OUTPUT_CAP_PROFILE_VERSIONS,
    ENGINEERING_REPAIR_ENABLED_PROFILE_VERSIONS,
    LEGACY_DECISION_PROMPT_PROFILE,
    max_output_tokens_for_profile,
    max_parse_repairs_for_profile,
)
from core.tool_agent.registry import (
    RegisteredTool,
    ToolHandler,
    ToolRegistry,
)
from core.tool_agent.runtime import ToolAgentRuntime
from core.tool_agent.runtime_models import (
    AGENT_DUPLICATE_TOOL_CALL,
    AGENT_TOOL_ERROR_LIMIT,
    INSUFFICIENT_EVIDENCE_TO_FINALIZE,
    AgentDecisionProvider,
    DecisionControlState,
    DecisionContextItem,
    EngineeringEvidence,
    KnowledgeEvidence,
    RuntimeTraceEvent,
    ToolAgentBudget,
    ToolAgentRunResult,
)
from core.tool_agent.tools import (
    CALCULATOR_SPEC,
    CODE_SEARCH_SPEC,
    KNOWLEDGE_SEARCH_SPEC,
    READ_PROJECT_CONTEXT_SPEC,
    CalculatorHandler,
    CodeSearchHandler,
    KnowledgeSearchHandler,
    ReadProjectContextHandler,
    CHANGED_FILES_SPEC,
    GIT_DIFF_SPEC,
    ChangedFilesHandler,
    GitDiffHandler,
    FIND_TESTS_SPEC,
    FindTestsHandler,
    is_test_path,
)

__all__ = [
    "ToolSpec",
    "ToolCall",
    "ToolObservation",
    "ToolHandler",
    "RegisteredTool",
    "ToolRegistry",
    "ToolExecutor",
    "UNKNOWN_TOOL",
    "INVALID_TOOL_ARGUMENTS",
    "TOOL_PERMISSION_DENIED",
    "TOOL_EXECUTION_FAILED",
    "PROJECT_CONTEXT_PATH_NOT_ALLOWED",
    "PROJECT_CONTEXT_FILE_NOT_FOUND",
    "PROJECT_CONTEXT_LINE_OUT_OF_RANGE",
    "PROJECT_CONTEXT_FILE_UNREADABLE",
    "GIT_REPOSITORY_UNAVAILABLE",
    "GIT_REF_INVALID",
    "GIT_PATH_NOT_ALLOWED",
    "GIT_DIFF_UNAVAILABLE",
    "GIT_COMMAND_FAILED",
    "TOOL_RESULT_INVALID",
    "TOOL_BUDGET_EXCEEDED",
    "ACTION_PARSE_FAILED",
    "ACTION_PROVIDER_ERROR",
    "ACTION_TIMEOUT",
    "AGENT_BUDGET_EXCEEDED",
    "TOOL_ERROR_CODES",
    "AGENT_ERROR_CODES",
    "TOOL_AGENT_ERROR_CODES",
    "TOOL_OBSERVATION_STATUSES",
    "ToolExecutionError",
    "json_deep_copy",
    "CALCULATOR_SPEC",
    "CODE_SEARCH_SPEC",
    "KNOWLEDGE_SEARCH_SPEC",
    "READ_PROJECT_CONTEXT_SPEC",
    "CalculatorHandler",
    "CodeSearchHandler",
    "KnowledgeSearchHandler",
    "ReadProjectContextHandler",
    "CHANGED_FILES_SPEC",
    "GIT_DIFF_SPEC",
    "ChangedFilesHandler",
    "GitDiffHandler",
    "FIND_TESTS_SPEC",
    "FindTestsHandler",
    "is_test_path",
    "build_readonly_tool_registry",
    "build_tool_agent_runtime",
    "FROZEN_TOOL_PROVIDER",
    "FROZEN_TOOL_MODEL",
    "AgentAction",
    "ToolCallAction",
    "FinalAnswerAction",
    "RefuseAction",
    "AgentDecisionOutcome",
    "AgentDecisionCallMetadata",
    "OpenAICompatibleAgentDecisionProvider",
    "DecisionPromptProfile",
    "LEGACY_DECISION_PROMPT_PROFILE",
    "ENGINEERING_DECISION_PROMPT_PROFILE",
    "ENGINEERING_DECISION_PROMPT_SHA256",
    "ENGINEERING_DECISION_PROMPT_V2_PROFILE",
    "ENGINEERING_DECISION_PROMPT_V2_SHA256",
    "ENGINEERING_DECISION_PROMPT_V3_PROFILE",
    "ENGINEERING_DECISION_PROMPT_V3_SHA256",
    "ENGINEERING_MAX_OUTPUT_TOKENS",
    "ENGINEERING_OUTPUT_CAP_PROFILE_VERSIONS",
    "ENGINEERING_REPAIR_ENABLED_PROFILE_VERSIONS",
    "max_output_tokens_for_profile",
    "max_parse_repairs_for_profile",
    "strict_json_loads_no_duplicates",
    "parse_agent_action_text",
    "diagnose_agent_action_text",
    "ActionParseCategory",
    "ActionParseResult",
    "ToolAgentRuntime",
    "ToolAgentBudget",
    "ToolAgentRunResult",
    "EngineeringEvidence",
    "KnowledgeEvidence",
    "DecisionContextItem",
    "RuntimeTraceEvent",
    "AgentDecisionProvider",
    "DecisionControlState",
    "AGENT_DUPLICATE_TOOL_CALL",
    "AGENT_TOOL_ERROR_LIMIT",
    "INSUFFICIENT_EVIDENCE_TO_FINALIZE",
]
